In [1]:
import torch

When dealing with deeplearning frameworks we use tensors instead of numpy arrays

In [22]:
print("Creates Tensor filled with uninitialized data:")
x = torch.empty(3)
print(x)

print("\nCreates Tensor filled with samples from uniform distribution:")
x = torch.rand(2,2)
print(x)

print("\nCreates Tensor filled with samples from normal distribution:")
x = torch.randn(2,2,3)
print(x)

print("\nCreates Tensor filled with zeros:")
x = torch.zeros(3,2,3)
print(x)

print("\nCreates Tensor filled with ones:")
x = torch.ones(2,2)
print(x)

Creates Tensor filled with uninitialized data:
tensor([-7.1188e+25,  4.5831e-41,  4.0302e+12])

Creates Tensor filled with samples from uniform distribution:
tensor([[0.8624, 0.8351],
        [0.2469, 0.0810]])

Creates Tensor filled with samples from normal distribution:
tensor([[[-1.1695,  0.4887, -0.2376],
         [ 1.5155, -0.5743, -1.6992]],

        [[ 0.8939, -1.3539, -0.3936],
         [ 0.2024,  1.3877,  1.5122]]])

Creates Tensor filled with zeros:
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

Creates Tensor filled with ones:
tensor([[1., 1.],
        [1., 1.]])


---
Creating tensors from python structures:

In [40]:
x = torch.tensor([1,2,3], dtype=int)
print(x)

tensor([1, 2, 3])


---
Operations:

- torch.add
- torch.sub
- torch.div

In [41]:
x1 = torch.rand(2,2)
x2 = torch.rand(2,2)

z = x1 + x2
print(z)
z = torch.add(x1,x2)
print(z)

"""
Every function with _ makes inplace operation
"""
x1.add_(x2) 
print(x1)

tensor([[0.8700, 0.9575],
        [1.0683, 0.7643]])
tensor([[0.8700, 0.9575],
        [1.0683, 0.7643]])
tensor([[0.8700, 0.9575],
        [1.0683, 0.7643]])


In [42]:
x1[2:]

tensor([], size=(0, 2))